### ISSUE TITLE
前回のやぱちーISSUEなどを見返して、タスクリストを作る

### ISSUE THREAD

**Issue by uzulla** [uzulla/y8-2017-spring#11]
https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues

**Comment by motchang** [comment]
前回のものをのべつ幕なし一覧にしてみました

- [ ] [1](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/1) タスク
- [ ] [2](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/2) 開催日に必要な備品
- [x] [3](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/3) twitterや、サイトで使えるロゴ
- [x] [4](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/4) ボランティアスタッフスレ
- [x] [5](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/5) サイトにハッシュタグなどを記載する
- [ ] [6](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/6) 「YAPCとは？」というテキストを書く
- [ ] [7](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/7) オーディエンス応募フォーム作る
- [ ] [8](https://github.com/hachiojipm/yapcasia-8oji-2016mid/pull/8) 主催のとこ追記
- [x] [9](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/9) MS社員様（紙製）に持っていただく通行止めサイン
- [x] [10](https://github.com/hachiojipm/yapcasia-8oji-2016mid/pull/10) fix typo
- [ ] [11](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/11) 懇親会
- [ ] [12](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/12) 掲示物
- [ ] [13](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/13) タイムテーブル作成
- [ ] [14](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/14) 道案内コンテンツ
- [ ] [15](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/15) 写真
- [ ] [16](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/16) 録画
- [ ] [17](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/17) ボランティアスタッフ確定
- [ ] [18](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/18) 当日用スマホ向けポータルサイト
- [x] [19](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/19) サイトをJekyllあたりで作り直す
- [x] [20](https://github.com/hachiojipm/yapcasia-8oji-2016mid/pull/20) to be jekyll
- [x] [21](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/21) サイトにソーシャル系のボタンを設置する
- [x] [22](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/22) GHpages で_postsが無視されている
- [x] [23](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/23) チャットを用意する
- [ ] [24](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/24) ベストトーク賞を作る
- [ ] [25](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/25) 6/4 打ち合わせスレ
- [ ] [26](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/26) トーク採択
- [ ] [27](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/27) フロアマップ
- [ ] [28](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/28) 買った物スレ（メモ）
- [ ] [29](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/29) 参加応募ページ
- [ ] [30](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/30) インターネット担当者決める
- [ ] [31](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/31) 会場諸注意
- [ ] [32](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/32) スタッフ担当箇所リスト
- [ ] [33](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/33) 受付担当者を決める
- [ ] [34](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/34) スタッフ緊急連絡網（電話）
- [ ] [35](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/35) スタッフ識別章を考える
- [ ] [36](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/36) 飛び入りトラック
- [x] [37](https://github.com/hachiojipm/yapcasia-8oji-2016mid/pull/37) ページにソーシャルボタンの設置
- [ ] [38](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/38) 「スタッフのしおり」をつくる
- [ ] [39](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/39) 部屋担当心得
- [ ] [40](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/40) エントランス入館受付心得
- [ ] [41](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/41) ネット担当心得
- [ ] [42](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/42) 遊撃隊の心得
- [ ] [43](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/43) 不適切とは
- [ ] [44](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/44) スピーカーに通知する事柄をまとめる
- [ ] [45](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/45) 2日目の打ち上げ的なパーリーナイト
- [ ] [46](https://github.com/hachiojipm/yapcasia-8oji-2016mid/pull/46) スタッフ用のしおり作成
- [ ] [47](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/47) 設営作業
- [ ] [48](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/48) 撤収手順をまとめる
- [ ] [49](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/49) サイト：トーク募集中をクローズする
- [ ] [50](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/50) 当日トラック（仮）の説明ページ作る
- [ ] [51](https://github.com/hachiojipm/yapcasia-8oji-2016mid/pull/51) リポジトリの内容を明確にするため説明を追記
- [x] [52](https://github.com/hachiojipm/yapcasia-8oji-2016mid/pull/52) Chage to related path
- [ ] [53](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/53) タイムテーブルの方に「決定」ラベルが欲しい
- [x] [54](https://github.com/hachiojipm/yapcasia-8oji-2016mid/pull/54) fix link
- [ ] [55](https://github.com/hachiojipm/yapcasia-8oji-2016mid/pull/55) 飛び入りトラック書いた
- [ ] [56](https://github.com/hachiojipm/yapcasia-8oji-2016mid/pull/56) 飛び入りトラックのお知らせ記事書いた
- [ ] [57](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/57) Connpassのメッセージ機能経由で言うタスク
- [ ] [58](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/58) 登壇者が参加登録わすれていないかチェックする
- [ ] [59](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/59) タイムキーパーは機械にやらせるぞ
- [ ] [60](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/60) ボランティアスタッフ打合＆キックオフ懇親会 No2
- [ ] [61](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/61) 宴会大臣の募集
- [ ] [62](https://github.com/hachiojipm/yapcasia-8oji-2016mid/pull/62) 銅鑼についてのエントリーを書いてみた
- [ ] [63](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/63) タイムテーブルにLTのリストをのっける
- [ ] [64](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/64) ステッカー用のロゴの制作
- [ ] [65](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/65) トーク予定のあるスタッフのシフト調整
- [ ] [66](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/66) Macだと4:3になる事があるので、設定方法を追記する
- [ ] [67](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/67) 周辺の店をサイトに追記しておく
- [ ] [68](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/68) ビデオカメラ用の延長ケーブルを買う
- [ ] [69](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/69) 懇親会関連でツイートの必要なタスク
- [ ] [70](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/70) 懇親会の受付と誘導について考える
- [ ] [71](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/71) LTで日付移動依頼がきたので調整
- [ ] [72](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/72) 自動タイムスケジュール告知ボットをつくる
- [ ] [73](https://github.com/hachiojipm/yapcasia-8oji-2016mid/pull/73) 飛び入りトラックの情報をアップデート
- [ ] [74](https://github.com/hachiojipm/yapcasia-8oji-2016mid/pull/74) 飛び入りトラックのリンクを修正しました
- [ ] [75](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/75) アサインがされていないスタッフさんに人力個別連絡
- [ ] [76](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/76) リンクバックエントリを書く
- [ ] [77](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/77) Connpass抽選が完了したら即刻CSVを保存し、キャンセルでの補欠登録をブロックする
- [ ] [78](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/78) 前日準備
- [ ] [79](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/79) LT運営手順書
- [ ] [80](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/80) 最初のアナウンス文
- [ ] [81](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/81) 昼食、弁当を注文したい方スレ
- [ ] [82](https://github.com/hachiojipm/yapcasia-8oji-2016mid/pull/82) LT鳴り物についての記事
- [ ] [83](https://github.com/hachiojipm/yapcasia-8oji-2016mid/pull/83) 画像のリンク先間違えてた！
- [ ] [84](https://github.com/hachiojipm/yapcasia-8oji-2016mid/pull/84) 拡張子間違えてた！
- [ ] [85](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/85) 前日にまいんだーさんともくもく作業配信
- [ ] [86](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/86) トークに投票しようエントリを書く
- [ ] [87](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/87) 各所リーダーにおたのみ申す事
- [ ] [88](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/88) 懇親会キャンセルがのびているのでつらい
- [ ] [89](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/89) 7/3(日)懇親会、参加者が伸びたので店に連絡
- [ ] [90](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/90) 動画公開不可や、ヤバそうなのを集める
- [ ] [91](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/91) 落し物を再度アナウンス
- [ ] [92](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/92) 写真選定
- [ ] [93](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/93) 動画公開
- [ ] [94](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/94) 動画公開順考える
- [ ] [95](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/95) ブログリンク
- [ ] [96](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/96) クローズエントリ
- [ ] [97](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/97) 「こうしたらよかった」、「これはよかった」報告スレ
- [ ] [98](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/98) 公式系まとめ
- [ ] [99](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/99) 登壇者スライドまとめ
- [ ] [100](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/100) 感想エントリまとめ
- [ ] [101](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/101) トップなどをクローズ状態に変更
- [ ] [102](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/102) スライド公開したなら、募集ISSUEに追記してくださいと告知する
- [ ] [103](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/103) 投票サイトを落とす
- [ ] [104](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/104) Periscopeの評判を知りたい
- [ ] [105](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/105) ドタキャンになったLTをリストアップし、ラベルを剥がす
- [ ] [106](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/106) Connpassのメッセージでフォローアップ
- [ ] [107](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/107) 今回のSlack運用ノウハウをどこかにまとめる
- [ ] [108](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/108) 今回の質問方式はなかなか難しかったらしいけん
- [ ] [109](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/109) 投票君
- [ ] [110](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/110) 忘れ物を解決する
- [x] [111](https://github.com/hachiojipm/yapcasia-8oji-2016mid/pull/111) Add ravelll's blog entries
- [ ] [112](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/112) 動画のコツをまとめる
- [ ] [113](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/113) 当日の写真をzipか何かに固めてアップロードする
- [ ] [114](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/114) 終わる前に用意しておいたほうがよかったものや、すぐやるべきもの
- [ ] [115](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/115) サイトのアクセスについて（メモ
- [ ] [116](https://github.com/hachiojipm/yapcasia-8oji-2016mid/issues/116) TT生成とかにつかったしょうもないツールをどっかに上げる
